<?php
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2015/01/11
 * Time: 21:34
 */

namespace Chatbox\Database\Eloquent;

use Illuminate\Database\Eloquent\Model;
use Chatbox\Chatbox\Schema\Base as SchemaBase;

abstract class Base extends Model{

    /**
     * @var SchemaBase
     */
    protected $schema;

    public function __construct(array $attributes = array())
    {
        $this->schema = $this->getSchema();
        $this->table = $this->schema->getName();
        parent::__construct($attributes); // TODO: Change the autogenerated stub
    }

    abstract public function getSchema();


}